# Generated by Django 6.0.3 on 2026-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=50)),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text="Lien vers l'image", max_length=500, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('carburant', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_places', models.IntegerField(blank=True, null=True)),
                ('nb_portes', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('kilometrage', models.IntegerField(blank=True, help_text='Kilométrage actuel', null=True)),
                ('consommation', models.FloatField(blank=True, help_text='L/100km', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipements', models.TextField(blank=True, help_text='GPS, Climatisation, etc.', null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('est_promo', models.BooleanField(default=False)),
                ('reduction_promo', models.IntegerField(blank=True, help_text='Pourcentage de réduction (0-100)', null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
