# Generated by Django 6.0.3 on 2026-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='consommation',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='kilometrage',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='transmission',
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
