# Generated by Django 6.0.3 on 2026-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_remove_voiture_consommation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='image_url',
        ),
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
